name: CatSeedLogin
main: cc.baka9.catseedlogin.bukkit.CatSeedLogin
author: CatSeed
version: ${version}
softdepend: [Multiverse-Core, Citizens, Essentials, EssentialsSpawn, ProtocolLib]
api-version: 1.13
commands:
  login:
    description: 使用密码登录
    usage: /<command> 密码
    aliases: [l]

  catseedloginreload:
    description: 管理员管理指令
    usage: §a/<command>
    aliases: [cslogin]
    permission: catseedlogin.command.catseedlogin
